# name: A workflow for my Hello World file
# on: push
# jobs:
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "Mona"

name: Daily Poll Runner

on:
  push:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create a file
        run: |
          echo "This is the content of the new file" > new-file.txt
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"
          git add new-file.txt
          git commit -m "Created new file"
          git push origin HEAD:main